"""LangGraph state schema for the Retail Insights multi-agent workflow.

This module defines the state that flows through the agent graph,
persisted via PostgresSaver for durability and session management.
"""

from __future__ import annotations

import operator
from typing import Annotated, Literal

from langgraph.graph import MessagesState

# Type aliases for clarity
IntentType = Literal["query", "summarize", "chat", "clarify"]
QueryMode = Literal["query", "summarize", "chat"]
ValidationStatus = Literal["pending", "valid", "invalid", "failed"]


class RetailInsightsState(MessagesState):
    """State schema for the multi-agent workflow.

    Extends MessagesState to include message history with `add_messages` reducer.
    Custom fields track the workflow progression from user query to final answer.

    Attributes:
        user_query: The original natural language question from the user.
        query_mode: Requested mode of operation (query/summarize/chat).
        intent: Router's classification of user intent.
        intent_confidence: Confidence score of intent classification (0-1).
        clarification_question: Question to ask if intent is 'clarify'.
        generated_sql: SQL query generated by the SQL Generator agent.
        sql_explanation: Natural language explanation of the generated SQL.
        tables_used: List of tables referenced in the generated SQL.
        sql_is_valid: Whether the SQL passed validation checks.
        validation_status: Current validation state (pending/valid/invalid/failed).
        validation_errors: Accumulated list of validation error messages.
        retry_count: Number of SQL generation retry attempts.
        max_retries: Maximum allowed retry attempts before failing.
        query_results: JSON-serializable results from query execution.
        row_count: Number of rows returned by the query.
        execution_time_ms: Query execution time in milliseconds.
        execution_error: Error message if query execution failed.
        final_answer: Human-readable summary of the results.
        thread_id: Unique identifier for the conversation thread.
        user_id: Optional user identifier for multi-tenant scenarios.
        available_tables: List of tables available for querying.
        schema_context: Retrieved schema documentation for SQL generation.
    """

    # User input
    user_query: str
    query_mode: QueryMode

    # Router output
    intent: IntentType | None
    intent_confidence: float | None
    clarification_question: str | None

    # SQL Generator output
    generated_sql: str | None
    sql_explanation: str | None
    tables_used: list[str]

    # Validator output
    sql_is_valid: bool
    validation_status: ValidationStatus
    validation_errors: Annotated[list[str], operator.add]  # Accumulate errors
    retry_count: int
    max_retries: int

    # Executor output
    query_results: list[dict] | None  # JSON-serializable results
    row_count: int
    execution_time_ms: float
    execution_error: str | None

    # Summarizer output
    final_answer: str | None

    # Session management
    thread_id: str
    user_id: str | None

    # Schema context
    available_tables: list[str]
    schema_context: str

    # Tool-based schema discovery
    refined_schema_context: str | None
    discovered_tables: list[str]


def create_initial_state(
    user_query: str,
    thread_id: str,
    *,
    query_mode: QueryMode = "query",
    available_tables: list[str] | None = None,
    schema_context: str = "",
    user_id: str | None = None,
    max_retries: int = 3,
) -> RetailInsightsState:
    """Create an initial state for a new query workflow.

    Args:
        user_query: The natural language question from the user.
        thread_id: Unique identifier for the conversation thread.
        query_mode: Requested mode of operation. Defaults to "query".
        available_tables: List of available tables. Defaults to empty list.
        schema_context: Schema documentation for SQL generation. Defaults to "".
        user_id: Optional user identifier. Defaults to None.
        max_retries: Maximum SQL generation retries. Defaults to 3.

    Returns:
        A fully initialized RetailInsightsState with default values.
    """
    return RetailInsightsState(
        # Messages (from MessagesState)
        messages=[],
        # User input
        user_query=user_query,
        query_mode=query_mode,
        # Router output
        intent=None,
        intent_confidence=None,
        clarification_question=None,
        # SQL Generator output
        generated_sql=None,
        sql_explanation=None,
        tables_used=[],
        # Validator output
        sql_is_valid=False,
        validation_status="pending",
        validation_errors=[],
        retry_count=0,
        max_retries=max_retries,
        # Executor output
        query_results=None,
        row_count=0,
        execution_time_ms=0.0,
        execution_error=None,
        # Summarizer output
        final_answer=None,
        # Session management
        thread_id=thread_id,
        user_id=user_id,
        # Schema context
        available_tables=available_tables or [],
        schema_context=schema_context,
        # Tool-based schema discovery
        refined_schema_context=None,
        discovered_tables=[],
    )
